name: developer_romantan
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  screen:
  flame:
  box2d_flame:
  sensors:
  pedantic:
  theseus:
  url_launcher:
  shared_preferences:
  wakelock:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  assets:
    - assets/images/ninja.png
    - assets/images/ninja/run-000.png
    - assets/images/ninja/run-001.png
    - assets/images/ninja/run-002.png
    - assets/images/ninja/run-003.png
    - assets/images/ninja/run-004.png
    - assets/images/ninja/run-005.png
    - assets/images/ninja/run-006.png
    - assets/images/ninja/run-007.png
    - assets/images/ninja/run-008.png
    - assets/images/ninja/run-009.png
    - assets/images/ninja/idle-000.png
    - assets/images/ninja/idle-001.png
    - assets/images/ninja/idle-002.png
    - assets/images/ninja/idle-003.png
    - assets/images/ninja/idle-004.png
    - assets/images/ninja/idle-005.png
    - assets/images/ninja/idle-006.png
    - assets/images/ninja/idle-007.png
    - assets/images/ninja/idle-008.png
    - assets/images/ninja/idle-009.png
    - assets/images/ninja/glide-000.png
    - assets/images/ninja/glide-001.png
    - assets/images/ninja/glide-002.png
    - assets/images/ninja/glide-003.png
    - assets/images/ninja/glide-004.png
    - assets/images/ninja/glide-005.png
    - assets/images/ninja/glide-006.png
    - assets/images/ninja/glide-007.png
    - assets/images/ninja/glide-008.png
    - assets/images/ninja/glide-009.png
    - assets/images/ninja/jump-000.png
    - assets/images/ninja/jump-001.png
    - assets/images/ninja/jump-002.png
    - assets/images/ninja/jump-003.png
    - assets/images/ninja/jump-004.png
    - assets/images/ninja/jump-005.png
    - assets/images/ninja/jump-006.png
    - assets/images/ninja/jump-007.png
    - assets/images/ninja/jump-008.png
    - assets/images/ninja/jump-009.png
    - assets/images/layers/layer_07_cropped.png
    - assets/images/layers/layer_07_cropped_mark.png
    - assets/images/layers/layer_01.png
    - assets/images/layers/layer_02.png
    - assets/images/layers/layer_03.png
    - assets/images/layers/layer_04.png
    - assets/images/layers/layer_05.png
    - assets/images/layers/layer_06.png
    - assets/images/layers/layer_07.png
